"""empty message

Revision ID: ccc285b369ca
Revises: fd35602ee179
Create Date: 2022-06-14 17:55:27.684476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccc285b369ca'
down_revision = 'fd35602ee179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('person', sa.Column('name', sa.String(), nullable=False))
    op.alter_column('person', 'completed', nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'name')
    # ### end Alembic commands ###
